name: ww_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_drawing_board:
    path: plugins/flutter_drawing_board-master
  flutter_svg: ^2.0.10+1
  image_gallery_saver: ^2.0.3  
  super_tooltip: ^2.0.7
  get: ^4.6.6
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
